"""add pickers

Revision ID: b4f99ce087e3
Revises: 68cbf91cc66c
Create Date: 2026-02-01 17:41:28.966475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4f99ce087e3'
down_revision: Union[str, Sequence[str], None] = '68cbf91cc66c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pickers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pickers_room_id'), 'pickers', ['room_id'], unique=False)
    op.create_table('picker_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('picker_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['picker_id'], ['pickers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_picker_options_picker_id'), 'picker_options', ['picker_id'], unique=False)
    op.create_table('pick_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('picker_id', sa.Integer(), nullable=False),
    sa.Column('picked_option_id', sa.Integer(), nullable=True),
    sa.Column('requested_by', sa.Integer(), nullable=True),
    sa.Column('commit_hash', sa.String(length=64), nullable=False),
    sa.Column('reveal_seed', sa.String(length=64), nullable=False),
    sa.Column('algo_version', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['picked_option_id'], ['picker_options.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['picker_id'], ['pickers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pick_events_commit_hash'), 'pick_events', ['commit_hash'], unique=False)
    op.create_index(op.f('ix_pick_events_picker_id'), 'pick_events', ['picker_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pick_events_picker_id'), table_name='pick_events')
    op.drop_index(op.f('ix_pick_events_commit_hash'), table_name='pick_events')
    op.drop_table('pick_events')
    op.drop_index(op.f('ix_picker_options_picker_id'), table_name='picker_options')
    op.drop_table('picker_options')
    op.drop_index(op.f('ix_pickers_room_id'), table_name='pickers')
    op.drop_table('pickers')
    # ### end Alembic commands ###
